config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/login',   to: 'static_pages#login'
  get  '/signup',  to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/user.rb
class User < ApplicationRecord::Base
    attr_accessible :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception

  def hello
      
    render html: "hello, world!"
    
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
    #returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <!--<nav>-->
  <!--  <ul>-->
  <!--    <li><%= link_to "About",   about_path %></li>-->
  <!--    <li><%= link_to "Contact", contact_path %></li>-->
  <!--    <li><a href="http://news.railstutorial.org/">News</a></li>-->
  <!--  </ul>-->
  <!--</nav>-->
  
  
<div class="row">
    <div class="column2">
      <h3><b>Contact us</b></h3>
    <div class="column1">
      <form action="/action_page.php">
        <label for="name">Name</label>
        <input type="text" id="name" name="name" placeholder="Your name..">
        <label for="email">Email</label>
        <input type="text" id="email" name="email" placeholder="Your email">
       
        <label for="message">Message</label>
        <textarea id="message" name="message" placeholder="Write something.." style="height:50px"></textarea>
        <input type="submit" value="Send">
      </form>
      <br>
      <p>Tel: 0123456789</p>
      <p>fax: 0123456</p>
      <p>Email: junliang.jiang@rmit.edu.au</p>
    </div>
    </div>
     <div class="column2">
      <h3><b>General Inquiries </b></h3>
      <br>
      <p>Andy Song</p>
      <p>Junliang Jiang</p>
      <p>Ali</p>
    </div>
    <div class="column2">
      <h3><b>Useful Links </b></h3>
      <br>
      <p>RMIT Course</p>
      <p>RMIT Help Desk</p>
      <p>RMIT International</p>
    </div>
    <div class="column2">
      <h3><b>Media </b></h3>
      <br>
      <p>Youtube</p>
      <p>Twitter</p>
      <p>Facebook</p>
      <p>Instagram</p>
      <p>Skype</p>
    </div>

</div>


</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "yourcourse", root_path, id: "logo" %>
    
    <div class ="nav navbar-nav navbar-right">
        
        <div class="dropdown">
        <button class="dropbtn">Category</button>
        <div class="dropdown-content">
        <a href="#">Web development</a>
        <a href="#">Java</a>
        <a href="#">Full Stack Dev</a>
         <a href="#">iOS Engineering</a>
        </div>
      </div>
       <div class="dropdown">
        <button class="dropbtn">Location</button>
        <div class="dropdown-content">
        <a href="#">14.10.31</a>
        <a href="#">F14.08.26</a>
         <a href="#">14.10.30</a>
        </div>
        </div>
       
            <input type = "button" class="btn1" value="Log In">
        
      </div>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About | Ruby on Rails Tutorial Sample App') %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact | Ruby on Rails Tutorial Sample App') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help | Ruby on Rails Tutorial Sample App') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home | Ruby on Rails Tutorial Sample App') %>
<div class="center jumbotron">
  <h1>Welcome to Your Course App</h1>

  <h2>
    This is the home page for RAD Assignment 2
    
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>


  
  <div class="row">
    <div class="column">
      <h3><b>View Course as Guest User</b></h3>
      <p>Browse and view courses as a guest and sign up later</p>
        <%= link_to "Browse all Courses", '#', class: "btn btn-lg btn-primary" %>
    </div>
    <div class="column">
      <h3><b>Sign in to your account</b></h3>
      <p>Update your courses, rate course, view coordinator informations</p>
        <%= link_to "Log in to your account", '#', class: "btn btn-lg btn-primary" %>
    </div>
  </div>
  

app/views/static_pages/signup.html.erb
<% provide(:title, 'Signup | Ruby on Rails Tutorial Sample App') %>
<h1>Signup</h1>
<p>
  Signup Page
</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>